apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend
  namespace: tracking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-frontend
  template:
    metadata:
      labels:
        app: admin-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret   
      containers:
        - name: admin
          image: ghcr.io/softwarestacksolutions/admin-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
